learningTemplates/basicApp/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from basicApp import views

# TEMPLATE TAGGING
app_name = 'basicApp'

urlpatterns = [
    url(r'^relative/$',views.relative, name='relative'),
    url(r'^other/$',views.other, name='other'),
]

learningTemplates/learningTemplates/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from basicApp import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basicApp/',include('basicApp.urls'))
]

learningTemplates/basicApp/models.py
from django.db import models

# Create your models here.

learningTemplates/basicApp/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicApp/index.html',context_dict)

def other(request):
    return render(request,'basicApp/other.html')

def relative(request):
    return render(request,'basicApp/relativeUrl.html')

learningTemplates/templates/basicApp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
      <meta charset="utf-8">
      <title>Base</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar=static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-brand" href="{% url 'basicApp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      <!-- Tudo que eu quero extender tem que ficar fora da página  -->
      {% endblock %}

    </div>
  </body>
</html>

learningTemplates/templates/basicApp/index.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Index</h1>
    <h2>Django Level 4</h2>

    <h1>{{ text|upper }}</h1>
    <h1>{{ number|add:"99" }}</h1>

    {% endblock %}

learningTemplates/templates/basicApp/other.html
<!DOCTYPE html>

{% extends "basicApp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>Django Level 4</h2>
    {% endblock %}

learningTemplates/templates/basicApp/relativeUrl.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
      <meta charset="utf-8">
      <title>Relative</title>
      <link rel = "stylesheet" href="{% static "css/myColor.css" %}" />
  </head>
  <body>
    <h1>Welcome to RelativeURL</h1>
    <h2>Django Level 4</h2>
    <a href="{% url 'basicApp:other' %}"> The Other Page </a>
    <p><a href="{% url 'admin:index' %}"> Admin Index </a></p>
    <p><a href="{% url 'index' %}"> Index </a></p>
  </body>
</html>